### ISSUE TITLE
Give your project a meaningful name

### ISSUE THREAD

**Issue by fabianmoronzirfas** [edgalindo/01_Analog-Fractals#1]
Hi @edgalindo please come up with a meaningful name for your project. Something that stands out. Maybe something your final result resembles to.

**Comment by edgalindo** [comment]
Thx for the suggestion:-)

**Comment by fabianmoronzirfas** [comment]
The suggestion was also about changing the name of the repo. ;)

**Comment by edgalindo** [comment]
yep:-)
